examples: don't rely on cup being installed
use the cup .jar in lib/

diff --git a/jflex/examples/interpreter/Makefile b/jflex/examples/interpreter/Makefile
--- a/jflex/examples/interpreter/Makefile
+++ b/jflex/examples/interpreter/Makefile
@@ -9,12 +9,19 @@
 #    starts the program on a test example
 #                                                                     
 
+JAVA=java
+JAVAC=javac
+JFLEX=../../bin/jflex
+CUPJAR=../../lib/java-cup-11a.jar
+CUP=$(JAVA) -jar $(CUPJAR)
+CP=.:$(CUPJAR)
 
+default: test
 
 .SUFFIXES: $(SUFFIXES) .class .java
 
 .java.class:
-	javac $*.java
+	$(JAVAC) -cp $(CP) $*.java
 
 FILE=	Yylex.java      parser.java    sym.java \
 	SymTab.java	AST.java \
@@ -26,9 +33,11 @@ FILE=	Yylex.java      parser.java    sym.java \
 	Main.java \
 	SymtabEntry.java STEfun.java	STEvar.java
 
+run: output.txt
 
-run: all
-	java Main < example.as
+output.txt: all
+	$(JAVA) -cp $(CP) Main < example.as > output.txt
+	cat output.txt
 
 all: Yylex.java parser.java $(FILE:java=class)
 
@@ -36,7 +45,10 @@ clean:
 	rm -f *.class *~ *.bak Yylex.java parser.java sym.java
 
 Yylex.java: scanner.flex
-	../../bin/jflex scanner.flex
+	$(JFLEX) scanner.flex
 
 parser.java: parser.cup
-	java java_cup.Main -interface < parser.cup
+	$(CUP) -interface < parser.cup
+
+test: output.txt
+	@(diff output.txt output.good && echo "Test OK!") || echo "Test failed!"
